[package]
name = "enano-web-test"
version = "0.5.1"
edition = "2024"
license = "MIT"
repository = "https://github.com/Data5tream/enano-web-test"
description = "Minimal web service for testing networking software and setups"
readme = "README.md"

[lints.clippy]
pedantic = "warn"

[dependencies]
axum = { version = "0.8.9", features = ["tracing"] }
tokio = { version = "1.53.1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.7.1", features = ["trace"] }
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
